#!/bin/bash
mv bak/Files.Mod ./ 2> /dev/null
mv bak/Out.Mod ./ 2> /dev/null
./oxpc -rs M.Mod
./oxpc -rs Files.Mod
./oxpc -rs Fonts.Mod
./oxpc -rs Texts.Mod
./oxpc -rs Out.Mod
./oxpc -rs OXS.Mod
./oxpc -rs OXB.Mod
./oxpc -rs OXT.Mod
./oxpc -rs OXX.Mod
./oxpc -rs OXG.Mod
./oxpc -rs OXP.Mod
