/*GENERATED BY OBNC 0.16.1*/

#include <obnc/Out.h>
#include ".obnc/OXP.h"
#include <obnc/OBNC.h>

#define OBERON_SOURCE_FILENAME "oxpc.Mod"

static OXP__FileName_ f_;
static OXP__Options_ o_;
static int i,n;

#if OBNC_CONFIG_TARGET_EMB
int main(void)
{
	OBNC_Init(0, NULL);
#else
int main(int argc, char *argv[])
{

    if ((argc>1)&&(argc<4)){
	OBNC_Init(argc, argv);
#endif
	Out__Init();
	OXP__Init();
	o_[0]=0;
	if(argc==3){
	    for (i=0;i<8;i++){o_[i]=argv[1][i];} o_[7]=0;
		n=2;
	}else{
		n=1;
	}
	for (i=0;i<32;i++){f_[i]=argv[n][i];} f_[31]=0;

	OXP__Compile_(f_, 32, o_, 8);
    }else{
	    printf("Usage: oxpc [-options] sourcefile.\n");
	    printf("\n"); 
	    printf("   Architecture options:\n"); 
	    printf("      r  RISC5  \n");  
	    printf("      R  ERISC5 \n");  
	    printf("      I  X8664  \n");  
	    printf("      A  ARM64  \n");  
	    printf("      a  ARM32  \n");  
	    printf("      C  CORTEX4\n");  
	    printf("      c  CORTEX0\n");  
	    printf("      V  RISCV64\n");  
	    printf("      v  RISCV32\n");  
	    printf("      W  WASM   \n");  
	    printf("\n"); 
	    printf("   Binary File Options:\n"); 
	    printf("      n  raw    \n");  
	    printf("      O  rsc64  \n");  
	    printf("      o  rsc32  \n");  
	    printf("      E  elf64  \n");  
	    printf("      e  elf32  \n");  
	    printf("      m  macho  \n");  
	    printf("      P  pe64   \n");  
	    printf("      p  pe32   \n");  
	    printf("\n"); 
	    printf("   Symbol File Options:\n"); 
	    printf("      s  newSF  \n"); 
    }
    return 0;
}
