/*GENERATED BY OBNC 0.16.1*/

#include <obnc/Out.h>
#include ".obnc/OXP.h"
#include <obnc/OBNC.h>

#define OBERON_SOURCE_FILENAME "oxpc.Mod"

static OXP__FileName_ f_;
static OXP__Options_ o_;
static int i,n;

#if OBNC_CONFIG_TARGET_EMB
int main(void)
{
	OBNC_Init(0, NULL);
#else
int main(int argc, char *argv[])
{

    if ((argc>1)&&(argc<4)){
	OBNC_Init(argc, argv);
#endif
	Out__Init();
	OXP__Init();
	o_[0]=0;
	if(argc==3){
	    for (i=0;i<8;i++){o_[i]=argv[1][i];} o_[7]=0;
		n=2;
	}else{
		n=1;
	}
	for (i=0;i<32;i++){f_[i]=argv[n][i];} f_[31]=0;

	OXP__Compile_(f_, 32, o_, 8);
    }else{
	    printf("Usage: oxpc [-options] sourcefile.\n");
    }
    return 0;
}
